package interfaz;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author usr
 */
public class Interfaz extends javax.swing.JFrame {
    
    private File f;
    private Manejador m;
    private HashMap<String, ArrayList<String>> map;

    /**
     * Creates new form Practica3
     */
    public Interfaz() {
        
        initComponents();
        
        m = new Manejador();
        
        setTitle("Diccionario de sinónimos");
        
        setLocationRelativeTo(null);

        setResizable(false);
        
        //String cadena = "";
        //for(String clave: map.keySet()){
        
            //cadena += clave + " -> " + map.get(clave) + "\n";
        
        //}

        texto.setText("\n   Sinónimos:\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        editorClaves = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        eliminarClave = new javax.swing.JButton();
        clave = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        editorValores = new javax.swing.JTextField();
        anadir = new javax.swing.JButton();
        eliminarValor = new javax.swing.JButton();
        claveActual = new javax.swing.JTextField();
        palabraActual = new javax.swing.JTextField();
        ayuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sinonimos = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        archivos = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(225, 225, 245));

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(225, 225, 245));
        texto.setColumns(5);
        texto.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        texto.setForeground(new java.awt.Color(47, 2, 2));
        texto.setLineWrap(true);
        texto.setRows(5);
        texto.setTabSize(2);
        texto.setBorder(null);
        panel.setViewportView(texto);

        editorClaves.setBackground(new java.awt.Color(225, 225, 245));
        editorClaves.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editorClaves.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editorClaves.setBorder(null);
        editorClaves.setPreferredSize(new java.awt.Dimension(100, 25));

        buscar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        buscar.setForeground(new java.awt.Color(51, 51, 51));
        buscar.setText("Buscar");
        buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        eliminarClave.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        eliminarClave.setForeground(new java.awt.Color(255, 0, 0));
        eliminarClave.setText("Borrar");
        eliminarClave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        clave.setEditable(false);
        clave.setBackground(new java.awt.Color(225, 225, 245));
        clave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clave.setForeground(new java.awt.Color(0, 0, 204));
        clave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clave.setText("Clave");
        clave.setBorder(null);
        clave.setOpaque(false);
        clave.setPreferredSize(new java.awt.Dimension(50, 25));

        valor.setEditable(false);
        valor.setBackground(new java.awt.Color(225, 225, 245));
        valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor.setForeground(new java.awt.Color(0, 0, 204));
        valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor.setText("Valor");
        valor.setBorder(null);
        valor.setOpaque(false);
        valor.setPreferredSize(new java.awt.Dimension(50, 25));
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        editorValores.setBackground(new java.awt.Color(225, 225, 245));
        editorValores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editorValores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editorValores.setBorder(null);
        editorValores.setPreferredSize(new java.awt.Dimension(100, 25));

        anadir.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        anadir.setForeground(new java.awt.Color(51, 51, 51));
        anadir.setText("Añadir");
        anadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarValor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        eliminarValor.setForeground(new java.awt.Color(255, 0, 0));
        eliminarValor.setText("Borrar");
        eliminarValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        claveActual.setEditable(false);
        claveActual.setBackground(new java.awt.Color(225, 225, 245));
        claveActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        claveActual.setForeground(new java.awt.Color(47, 2, 2));
        claveActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        claveActual.setText("Reajustable ");
        claveActual.setBorder(null);
        claveActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActualActionPerformed(evt);
            }
        });

        palabraActual.setEditable(false);
        palabraActual.setBackground(new java.awt.Color(225, 225, 245));
        palabraActual.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        palabraActual.setForeground(new java.awt.Color(30, 1, 1));
        palabraActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        palabraActual.setText("Palabra actual:");
        palabraActual.setBorder(null);
        palabraActual.setOpaque(false);

        ayuda.setBackground(new java.awt.Color(225, 225, 245));
        ayuda.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        ayuda.setForeground(new java.awt.Color(0, 0, 204));
        ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pregunta.png"))); // NOI18N
        ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ayuda.setContentAreaFilled(false);
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(225, 225, 245));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/palabras.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 40));

        sinonimos.setEditable(false);
        sinonimos.setBackground(new java.awt.Color(225, 225, 245));
        sinonimos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        sinonimos.setForeground(new java.awt.Color(30, 1, 1));
        sinonimos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sinonimos.setText("Sinónimos:");
        sinonimos.setBorder(null);
        sinonimos.setOpaque(false);

        archivos.setText("  Archivos");

        abrir.setText("Abrir archivo");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        archivos.add(abrir);

        cerrar.setText("Cerrar archivo");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        archivos.add(cerrar);

        guardar.setText("Guardar");
        archivos.add(guardar);

        menu.add(archivos);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editorClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editorValores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(claveActual, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sinonimos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palabraActual, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(palabraActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claveActual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editorClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editorValores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Abrir archivo");
        chooser.setFileFilter(new FileNameExtensionFilter("csv", "CSV"));
           
        if(chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            
            File archivo = chooser.getSelectedFile();
            
            try{
                
                if(archivo != null){
                    
                    f = archivo;
                            
                    m.leer(archivo);
                    
                }
                
            }catch(Exception e){
                
                JOptionPane.showConfirmDialog(null, "No se pudo abrir el archivo", 
                   "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
    }//GEN-LAST:event_abrirActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        
        f = null;
        m = new Manejador();
        cerrar.setEnabled(false);
        texto.setEnabled(false);

    }//GEN-LAST:event_cerrarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        String palabraBuscada = editorClaves.getText();
        
        if(palabraBuscada.equals("")){} else {
        
            claveActual.setText(editorClaves.getText());
        
            String sinonimos = m.buscar(editorClaves.getText());
        
            texto.setText(sinonimos);
            
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void claveActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton anadir;
    private javax.swing.JMenu archivos;
    private javax.swing.JButton ayuda;
    private javax.swing.JButton buscar;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField claveActual;
    private javax.swing.JTextField editorClaves;
    private javax.swing.JTextField editorValores;
    private javax.swing.JButton eliminarClave;
    private javax.swing.JButton eliminarValor;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField palabraActual;
    private javax.swing.JScrollPane panel;
    private javax.swing.JTextField sinonimos;
    private javax.swing.JTextArea texto;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
